include: package:pedantic/analysis_options.yaml

analyzer: 
  exclude: [build/**]
linter: 
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - camel_case_extensions
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
